export type GhostPluginVersion = 'super' | 'free'

export type GhostPluginItem = {
  title: string
  href: string // relative to ghostplugins.com
  imageSrc: string
  price: string | null // $xx.xx for super plugins; null for free plugins
  salePrice: string | null // when badge === "sale"
  originalPrice: string | null // when badge === "sale"
  badge: 'sale' | null
  categories: string[]
  version: GhostPluginVersion
}

export const SUPER_PLUGINS: GhostPluginItem[] = [
  {
    title: 'Doodle Pen',
    href: '/products/p/doodle-pen',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1707954738398-T5KMUAS2Z41FXZN79XNY/doodle_light.png',
    price: '$20.00',
    salePrice: '$20.00',
    originalPrice: '$30.00',
    badge: 'sale',
    categories: [],
    version: 'super',
  },
  {
    title: 'Floating Header Navigation',
    href: '/products/p/floating-header-navigation',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1695527411871-HMY03LSW3ZAQ1N78WDU5/floating_header.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Pushed Down Header',
    href: '/products/p/pushed-down-header',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1673812940333-DKQ9TE4JU2XZYU7V9ECY/pushed_header_bottom.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Easy Header Navigation Icons',
    href: '/products/p/easy-header-navigation-icons',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680130904451-C49RI9ASFI6W4W6MLQMP/easy_header_nav_icons.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Confetti Pop! Form',
    href: '/products/p/confetti-pop-form',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680230196813-I4TSCOCC60LZP2764A97/conf_form.gif',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Confetti Pop! Buttons',
    href: '/products/p/confetti-pop-buttons',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1706996448632-4R2LS667R2YPR156GCHB/confetti_pop_button.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Click and Stack Images',
    href: '/products/p/click-and-stack-images',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1695521299955-N85CUPWO94QSHCUK7XEJ/click_stack.gif',
    price: '$30.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Logo Loading Screen (Bar)',
    href: '/products/p/logo-loading-screen-bar',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680139076621-RYZVRDNIQOI149ORA5SM/loading_bar_circ.gif',
    price: '$20.00',
    salePrice: '$20.00',
    originalPrice: '$30.00',
    badge: 'sale',
    categories: [],
    version: 'super',
  },
  {
    title: 'Logo Loading Screen (Circle)',
    href: '/products/p/logo-loading-screen',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680139338459-E7EJ7S62ADJDTC724T9C/circl_loading_dark_AdobeExpress.gif',
    price: '$20.00',
    salePrice: '$20.00',
    originalPrice: '$30.00',
    badge: 'sale',
    categories: [],
    version: 'super',
  },
  {
    title: 'Aiko Testimonial Slider',
    href: '/products/p/aiko-testimonial-slider',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680140258385-9LUDT2SY34FHW4KVNIGB/aiko.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Boldly Testimonial Slider',
    href: '/products/p/boldly-testimonial-slider',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680143410476-VCLIGB1LHL0JSMC0TZ4J/boldly.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Mood Board Images',
    href: '/products/p/mood-board',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1688672690629-Q4YE4MTLSDNMBQL87S6P/mood_paper.gif',
    price: '$30.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Hide and Seek Images',
    href: '/products/p/kuro-hover-image-list',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/77fb62ad-6069-4671-a36f-ee5d9b8eeb8b/hide_seek_paper_final.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Front Info and Image Slider',
    href: '/products/p/front-info-slider',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680168878677-KIBFLET1H8SHGXUX8U91/front.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Come Back Browser Tab',
    href: '/products/p/come-back-tab',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/0c41b126-90bb-44f2-9660-3dfcb9529ccf/comeback_tab.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Circ Button Hover Style',
    href: '/products/p/circ-button-hover-style',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/2eb1e1ba-f849-4296-a210-901e2d327ab1/bttn_circ.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Sale Tag Announcement Bar',
    href: '/products/p/sale-tag-announcement-bar',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/8deab42f-5293-4f0e-94d0-cc1a0a586e9a/sales_tags_announcement.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Four Corner Navigation 2.0',
    href: '/products/p/four-corner-navigation',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680673854469-CNB4JQVVMH1YQ3X30GOM/palette_nav.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Verification Pop Up',
    href: '/products/p/verification-pop-up',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680140935287-JOXB8UNQ8MR4S79BCU3Q/verify_example.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Kuro Image Hover List',
    href: '/products/p/kuro-image-hover-list',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/5cd101ca-4972-41fe-9b9a-e067d4b87f09/kuro_paper.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Copy To Clipboard',
    href: '/products/p/copy-to-clipboard',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1707952455978-HBIUPATRX8QRGNKVBO5F/copy_to_clipboard.png',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Percent Loading Screen',
    href: '/products/p/percent-loading-screen',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/bd237598-8462-4bf9-9650-75b07a362e7e/count_up.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Rotating Scroll Down Circle (7.1 Version)',
    href: '/products/p/rotating-scroll-down-circle-71-version',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1704349866461-I7TG0KUPPUPZRHTFH325/ezgif-4-fa145cfb51.gif',
    price: '$10.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Animated Number Counter',
    href: '/products/p/number-counter',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680169335344-L10D77XA42OR7HR5WRN9/number_counter.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Keito Image Changer',
    href: '/products/p/keito-image-changer',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680221926375-CCR8QNS1OZTC2MANSXS6/keito.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Taydio Image Changer',
    href: '/products/p/taydio-image-changer',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680221901562-VR9SACYOHUL9PDLM70KK/taydio%27.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Snappy Page Sections',
    href: '/products/p/snappy-page-sections',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680203286621-AYOESMPPQEKJDRIRYYS3/snappy.gif',
    price: '$20.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Claro Summary Block',
    href: '/products/p/claro-summary-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680160720815-YR9AQ0ANBFR6GKK9425G/claro_example.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Pokit Summary Block',
    href: '/products/p/pokit-summary-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680162752985-9EF6VAKMV470QO7Q4HHY/pokit.png',
    price: '$25.00',
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'super',
  },
  {
    title: 'Balance Summary Block',
    href: '/products/p/balance-summary-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1680219874624-0N1S9ZWONQRGUGSCU8LX/balance_paper.png',
    price: '$25.00',
    salePrice: '$25.00',
    originalPrice: '$5',
    badge: 'sale',
    categories: [
      'Site Header',
      'Various Elements',
      'Announcement',
      'Mobile Menu',
      'Blog and Posts',
    ],
    version: 'super',
  },
]
export const FREE_PLUGINS: GhostPluginItem[] = [
  {
    title: 'Solid Shadow Button - Site Header',
    href: '/free-plugins/header-button-solid-drop-shadow-style',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/245ad96b-cd1b-4cb3-bffc-c910f456c32b/site_header_drop_shadow.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Site Header'],
    version: 'free',
  },
  {
    title: 'Flip Over Icons - Social Links Block',
    href: '/free-plugins/flip-over-icons-social-links-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/f71b639a-7862-4b44-9783-3ffefd08d3de/flip_social_block.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Pushed Down Announcement Bar',
    href: '/free-plugins/announcement-bar-pushed-down',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/bf28e4f2-a467-4a08-9042-de439d5d06af/pushed_announcement.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Announcement'],
    version: 'free',
  },
  {
    title: 'Mini Announcement Bar',
    href: '/free-plugins/announcement-bar-mini-corner',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/ed7d62c0-c8d5-4ef6-9dfc-1260dc1936b8/announcement_mini_bar.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Announcement'],
    version: 'free',
  },
  {
    title: 'Replace Mobile Menu = Icon With Text',
    href: '/free-plugins/replace-mobile-menu-icon-with-text',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/d12bb97f-1902-4425-a467-7da264ca811c/mobile_menu_text.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Mobile Menu'],
    version: 'free',
  },
  {
    title: 'Text Highlight Color',
    href: '/free-plugins/text-highlight-color',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/b9bd1fad-f9ae-4861-8fba-3179546fde4d/text_highlight.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Move Nav To Top Corner - Mobile Menu',
    href: '/free-plugins/move-navigation-to-top-corner-mobile-menu',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1725515280010-Q47BRQRE5VGU7M4DTJRJ/move_nav_top.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Mobile Menu'],
    version: 'free',
  },
  {
    title: 'Tilted Hyperlinks',
    href: '/free-plugins/tilted-hyperlinks',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/49d8d17f-8110-4f42-9f06-9594ff50bee8/tilted_hyperlinks.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Blog and Posts'],
    version: 'free',
  },
  {
    title: 'Flipped Mirror Hyperlinks',
    href: '/free-plugins/flipped-mirror-hyperlinks',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/f651a0a0-336b-464c-b539-45c5f706f602/mirror_hyperlinks.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Move Over Hyperlinks',
    href: '/free-plugins/move-over-hyperlinks-text-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/fd62854a-e3c6-4e5e-9d9a-6442158cddeb/move_over_hyperlinks.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Dot Cursor',
    href: '/free-plugins/dot-cursor',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/05bbbfd5-a82e-43be-85b6-d96ceb580bf3/dot_cursor.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Slide Arrow Button (#2) - Button Block',
    href: '/free-plugins/slide-arrow-button-2-button-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/492a8f06-d0e1-43c4-9578-781cc14bd0a5/button_2.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Slide Arrow Button (#1) - Button Block',
    href: '/free-plugins/slide-arrow-button-1-button-block',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/1725838328500-GNKZCJQIICIC5J1D439L/button_1.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Emoji Cursor',
    href: '/free-plugins/emoji-cursor',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/79873dc1-1283-4a40-a194-b0cf03a58f8f/emoji_cursor.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Hyperlink External Arrow Icon (#3)',
    href: '/free-plugins/hyperlink-external-arrow-icon-3',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/eeb35401-ac2b-4016-aa30-b511c2e6e602/external_icon_3.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Hyperlink External Arrow Icon (#2)',
    href: '/free-plugins/hyperlink-external-arrow-icon-2',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/c6004120-672a-4ecb-85c3-aa7893dd82e9/external_icon_2.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Hyperlink External Arrow Icon (#1)',
    href: '/free-plugins/hyperlink-external-arrow-icon-1',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/2493f08f-8b6f-45cf-b4ae-d4c65e8154f6/external_icon_1.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Border Style - Image Block',
    href: '/free-plugins/image-block-border-radius',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/6f6620e4-c96d-4546-b550-c0578b626e98/image-block-border.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Solid Shadow Style - Image Block',
    href: '/free-plugins/image-block-solid-shadow-style',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/a9cfe2ba-6833-4742-81f1-0d8451af668d/image_block_solid_shadow.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Tilt Hover - Image Block',
    href: '/free-plugins/image-block-tilt-hover',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/f7487254-535a-4ac7-88cd-179ee4cd90ca/tilt_hover_image.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Rotating Logo - Site Header',
    href: '/free-plugins/rotating-header-logo',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/fbd1155e-6398-4e1a-8fc7-4d70599c8ba2/rotating_logo.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Site Header'],
    version: 'free',
  },
  {
    title: 'Logo and Navigation Divider Line',
    href: '/free-plugins/logo-and-navigation-divider-line',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/87e1f564-29a2-41c9-8478-2d82d4a86aa5/logo_divider.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Site Header'],
    version: 'free',
  },
  {
    title: 'Slashy Navigation - Site Header',
    href: '/free-plugins/slashy-navigation',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/0ff25d46-e9cb-43ee-a08c-620ba67b0169/slashy_nav.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Site Header'],
    version: 'free',
  },
  {
    title: 'Pagination Background Color - Blog Post',
    href: '/free-plugins/blog-pagination-background-color',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/c16990a1-8a66-4dbc-a8a8-800cb7470975/page_background_color.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Blog and Posts'],
    version: 'free',
  },
  {
    title: 'Hide Pagination - Blog Post',
    href: '/free-plugins/blog-hide-blog-post-pagination',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/dbb7b878-eff0-4a79-acfc-77677bd2f3c6/hide_blog_pag.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Blog and Posts'],
    version: 'free',
  },
  {
    title: 'Divider Lines Bettwen Links - Navigation Dropdown',
    href: '/free-plugins/divider-lines-between-folder-linksrqfolder',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/58c18cf4-a10a-4ca9-b0e0-d086c08a1b2b/folder_lines_divider%2Bcopy+%281%29.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Site Header'],
    version: 'free',
  },
  {
    title: 'Custom Scroll Bar Colors',
    href: '/free-plugins/custom-scroll-bar-colors',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/5b646093-dd6a-4c2f-bf35-e337a173e7ad/scroll_bar_custom.png',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: ['Various Elements'],
    version: 'free',
  },
  {
    title: 'Easy Vertical Text',
    href: '/free-plugins/text-block-vertical-style',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/4c6d18ba-a61d-4d92-ba96-cc573289f611/vertical_text.jpeg',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'Titled Scrolling Block',
    href: '/free-plugins/scrolling-block-tilted-style',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/362624a9-a217-4e5d-af43-8a4bf6c3e0b0/scrolling_tilt_block.gif',
    price: null,
    salePrice: null,
    originalPrice: null,
    badge: null,
    categories: [],
    version: 'free',
  },
  {
    title: 'House Icon (#02) - Mobile Menu',
    href: '/free-plugins/mobile-menu-icon-house-icon-02',
    imageSrc:
      'https://images.squarespace-cdn.com/content/v1/5ba5e044b10f25cb908c506f/652a9366-d005-4458-9def-e9c34d98abbc/house_2_icon.png',
    price: '$5',
    salePrice: '$5',
    originalPrice: '$10',
    badge: 'sale',
    categories: ['Mobile Menu'],
    version: 'free',
  },
]
